{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.monitoring.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: monitoring-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "kiali-operator.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.monitoring.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.monitoring.principals | toYaml | nindent 10 }}
{{- end }}