{{- if and .Values.networkPolicies.enabled .Values.cr.spec.external_services.tracing.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tempo-egress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: tempo
      podSelector:
        matchLabels:
          name: tempo
    ports:
    - port: 16686
{{- end }}