{{- if and .Values.networkPolicies.enabled (eq "openid" .Values.cr.spec.auth.strategy) }}
# needs tuning
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-sso-egress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
{{- end }}
