{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-ns
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {} # all pods
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector: {} # all pods in namespace
{{- end }}
