{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  ingress: []
  policyTypes:
    - Ingress
{{- end }}