{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: istio-controlplane
        podSelector:
          matchLabels:
            {{- toYaml .Values.networkPolicies.ingressLabels | nindent 12}}
      ports:
      - port: {{ .Values.port }}
{{- end }}
