{{- if and .Values.istio.enabled .Values.istio.mtls }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: default-kiali
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}