{{- /* Render Istio ServiceEntry for SSO */ -}}
{{- $authStrategy := dig "auth" "strategy" "token" .Values.cr.spec -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.sso.enabled (eq $authStrategy "openid") -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "kiali.hostnameFromUri" .Values.cr.spec.auth.openid.issuer_uri | replace "." "-" }}-service-entry
  namespace: {{ $.Release.Namespace }}
spec:
  exportTo:
    - "."
  hosts:
    - {{ include "kiali.hostnameFromUri" .Values.cr.spec.auth.openid.issuer_uri }}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
{{- end -}}

