{{- /* Render Istio ServiceEntry for Tracing (external) */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.cr.spec.external_services.tracing.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "kiali.hostnameFromUri" .Values.cr.spec.external_services.tracing.url | replace "." "-" }}-service-entry
  namespace: {{ $.Release.Namespace }}
spec:
  exportTo:
    - "."
  hosts:
    - {{ include "kiali.hostnameFromUri" .Values.cr.spec.external_services.tracing.url }}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
{{- end -}}

