apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "{{ .Values.host }}"
  gateways:
  - main.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.port | default "20001" }}
        host: kiali.{{ .Release.Namespace }}.svc.cluster.local
