suite: test network policies
templates:
  - templates/bigbang/network-policies.yaml
set:
  networkPolicies.enabled: true
tests:
  - it: should create network policies when enabled
    documentSelector:
      path: metadata.name
      value: default-ingress-deny-all
    asserts:
      - isKind:
          of: NetworkPolicy
      - equal:
          path: metadata.name
          value: default-ingress-deny-all